(()=>{const $=x=>document.getElementById(x),fmt=n=>new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(n);
function render(){let s=AMIRA.state.stats||{total:0,valid:0,workers:0,photos:0,gps:0,byWS:{},byBlock:{},byMat:{}};
$("trx").textContent=fmt(s.total);$("hk").textContent=fmt(s.workers);$("realization").textContent=fmt(s.valid);$("validRate").textContent=s.total?`Valid ${fmt(s.valid/s.total*100)}%`:"POC — menunggu data";$("evidence").textContent=s.valid?fmt(s.photos/s.valid*100)+"%":"0%";$("evidenceText").textContent=`${fmt(s.photos)} foto • ${fmt(s.gps)} GPS`;$("gpsCount").textContent=fmt(s.gps);$("materialCount").textContent=Object.keys(s.byMat).length;$("sourceBadge").textContent=s.total?`Amanda ${s.total} transaksi`:"POC — menunggu data";$("mapInfo").textContent=s.gps?`${fmt(s.gps)} titik GPS terdeteksi`:"Upload data untuk melihat GPS";
$("workstream").innerHTML=AMIRA.workstreams.map(w=>`<div class="ws"><div><b>${w}</b><span>${fmt(s.byWS[w]||0)}</span></div><div class="meter"><i style="width:${Math.min(100,(s.byWS[w]||0)/(s.valid||1)*100)}%"></i></div></div>`).join("")+`<div class="ws"><div><b>OTHER</b><span>${fmt(s.byWS.OTHER||0)}</span></div></div>`;
let mats=Object.entries(s.byMat).sort((a,b)=>b[1]-a[1]).slice(0,5);$("materialTable").innerHTML=mats.length?mats.map(([m,n])=>`<tr><td>${m}</td><td>—</td><td>${fmt(n)}</td></tr>`).join(""):`<tr><td colspan="3">Belum ada data</td></tr>`;$("balance").innerHTML=$("materialTable").innerHTML;
let bs=Object.entries(s.byBlock).sort((a,b)=>b[1]-a[1]).slice(0,8),mx=Math.max(...bs.map(x=>x[1]),1);$("blocks").innerHTML=bs.length?bs.map(([b,n])=>`<div class="block"><span>${b}</span><div><i style="width:${n/mx*100}%"></i></div><b>${fmt(n)}</b></div>`).join(""):"<p class='muted'>Belum ada transaksi.</p>";
$("activity").innerHTML=AMIRA.state.rows.filter(r=>r._valid).slice(0,15).map(r=>`<tr><td>${r.ATTTIME||r.S_TIME||"—"}</td><td>${r.NAMA||r.EMPCODE||r.EMPNO||"—"}</td><td>${r.JOBCODE||"—"}</td><td>${r.BLOKCODE||"—"}</td><td>${r.PHOTO_PATH||r.PHOTO_PATH2?"●":"—"}</td></tr>`).join("")||`<tr><td colspan="5">Upload Amanda CSV untuk melihat transaksi.</td></tr>`;
$("evidenceDonut").textContent=s.valid?fmt(s.photos/s.valid*100)+"%":"0%";$("evidenceList").innerHTML=`<div class="legend">● Foto <b>${fmt(s.photos)}</b></div><div class="legend">● GPS <b>${fmt(s.gps)}</b></div><div class="legend">● Tanpa foto <b>${fmt(Math.max(0,s.valid-s.photos))}</b></div>`;$("alerts").innerHTML=s.total?`<div class="alert info">ⓘ ${fmt(s.valid)} transaksi valid dari ${fmt(s.total)} baris.</div>`:`<div class="alert info">ⓘ Upload Master Rawat dan CSV Amanda untuk mengaktifkan engine.</div>`}
async function readFiles(files){return Promise.all([...files].map(f=>f.text()))}
$("uploadBtn").onclick=async()=>{let a=$("masterInput");a.click();a.onchange=async()=>{if(!a.files[0])return;let m=AMIRAParser.parseMaster(await a.files[0].text());let b=$("amandaInput");b.click();b.onchange=async()=>{let aa=(await readFiles(b.files)).map(AMIRAParser.parseAmanda);let jobs=new Map((m.sections.M_JOB||[]).map(r=>[String(r.JOBCODE||"").trim(),r]));let rows=aa.flat().map(r=>{let j=jobs.get(String(r.JOBCODE||"").trim())||{},ws=AMIRA.classify(r.JOBCODE,j.JOBNAME||j.DESCRIPTION||j.JOBDESC||"");return{...r,_job:j,_ws:ws,_valid:!!r.JOBCODE&&(!!r.EMPNO||!!r.NAMA)}}),v=rows.filter(r=>r._valid),workers=new Set(v.map(r=>r.EMPNO||r.EMPCODE||r.NAMA).filter(Boolean)),byWS={},byBlock={},byMat={};v.forEach(r=>{byWS[r._ws]=(byWS[r._ws]||0)+1;let bl=r.BLOKCODE||"—";byBlock[bl]=(byBlock[bl]||0)+1;let mat=r.MATERIAL||r.MATERIALCODE||r.ITEMBACODE||r._job.ITEMBACODE||"—";byMat[mat]=(byMat[mat]||0)+1});AMIRA.state={master:m,amanda:aa,jobs,rows,stats:{total:rows.length,valid:v.length,workers:workers.size,photos:v.filter(r=>r.PHOTO_PATH||r.PHOTO_PATH2).length,gps:v.filter(r=>AMIRA.num(r.LAT)||AMIRA.num(r.LONG)).length,byWS,byBlock,byMat}};render()}}};$("today").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});render()})();